### ISSUE TITLE
Automate notifying npm publisher using github actions package

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#490]
### **Description**

Currently the process to notify @MetaMask/npm-publishers on slack is manual. It would be great it was automated once a release was published

https://github.com/MetaMask/action-npm-publish

### **Technical Details**

- Add npm publish action to github workflows

### **Acceptance Criteria**

- After publishing @metamask-npm-publishers are notified in #metamask-dev

**Comment by Gudahtt** [comment]
I'd recommend copying over the new workflows from the module template: https://github.com/MetaMask/metamask-module-template

The new workflows include automated npm publishing as well, requiring just a button click from the npm admins rather than manual publishing.

We even have a tool for synchronizing with the module template: https://github.com/MetaMask/template-sync

**Comment by Gudahtt** [comment]
Though I think that would depend upon upgrading to Yarn v3 first. Looks like v1 is still used here.

**Comment by georgewrmarshall** [comment]
ok thanks for the excellent direction @Gudahtt 🙏

**Comment by georgewrmarshall** [comment]
This has been completed
